default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bath_hack_development
  username: <%= ENV.fetch("DB_USERNAME", ENV["USER"]) %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host:     <%= ENV.fetch("DB_HOST", "localhost") %>

test:
  <<: *default
  database: bath_hack_test
  username: <%= ENV.fetch("DB_USERNAME", ENV["USER"]) %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host:     <%= ENV.fetch("DB_HOST", "localhost") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
